from typing import List
from pydantic import BaseModel, Field
from config.llm_config import llm_designer
from tools.llm_helpers import clean_llm_response
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.prebuilt import create_react_agent

from agents.architect_agent import ArchitectOutput
from agents.stitch_mcp import StitchMCPClient
import json_repair

# ── Pydantic Models ────────────────────────────────────────────────────────────

class UIScreen(BaseModel):
    """Represents a generated UI screen."""
    name: str = Field(..., description="Name of the screen, e.g., 'Home', 'Dashboard'")
    description: str = Field(..., description="Description of the screen and its components")
    stitch_screen_url: str = Field(default="", description="The URL or resource name generated by Google Stitch")
    html_content: str = Field(default="", description="HTML content representation of the screen")

class UIDesignerOutput(BaseModel):
    """The final output from the UI Designer Agent."""
    project_name: str = Field(..., description="Name of the UI project")
    design_system_notes: str = Field(..., description="Notes on the generated design system (colors, typography, etc.)")
    screens: List[UIScreen] = Field(default_factory=list, description="List of generated UI screens")

# ── Prompts ────────────────────────────────────────────────────────────────────

UIDESIGNER_SYSTEM_PROMPT = """You are the UI Designer Agent of the development team.
Your job is to use the Google Stitch tools (available via functions) to generate the screens and the design system of the project based on the proposed architecture.

PROCESS TO FOLLOW:
1. Create a new project in Google Stitch (create_project) or use an existing one.
2. Generate the design system (create_design_system_from_design_md or another).
3. For each view required in the frontend of the architecture, use 'generate_screen_from_text' or 'create_screen' to build the UI.
4. When you have finished generating the screens, you MUST generate your final output by returning ONLY a structured JSON object that conforms to this format:

```json
{
  "project_name": "Name",
  "design_system_notes": "...",
  "screens": [
    {
      "name": "Home",
      "description": "...",
      "stitch_screen_url": "projects/XYZ/screens/123"
    }
  ]
}
```
Do not include any text outside the final JSON."""

# ── Public API ─────────────────────────────────────────────────────────────────

def run_ui_designer_agent(architect_output: ArchitectOutput, stitch_api_key: str) -> UIDesignerOutput:
    """Uses Google Stitch to design UI screens based on the architecture."""
    
    # Initialize Stitch MCP Tools
    stitch_client = StitchMCPClient(api_key=stitch_api_key)
    try:
        tools = stitch_client.get_tools()
        print(f"🔧 [UIDesigner] Loaded {len(tools)} Google Stitch tools.")
    except Exception as e:
        print(f"⚠️ [UIDesigner] Error loading Stitch tools: {e}. Running without tools.")
        tools = []
        
    llm = llm_designer
    
    agent = create_react_agent(llm, tools=tools)
    
    arch_json = architect_output.model_dump_json(indent=2)
    
    # Combine the system prompt with the human message as the first prompt
    prompt = f"{UIDESIGNER_SYSTEM_PROMPT}\n\nHere is the system architecture:\n{arch_json}\n\nUse Stitch tools to generate the screens, and then return the structured JSON."
    
    print("🎨 [UIDesigner] Generating screens with Google Stitch...")
    response = agent.invoke({"messages": [HumanMessage(content=prompt)]}, config={"recursion_limit": 10})
    
    final_message = response["messages"][-1].content
    
    # Parse the final JSON from the agent's last message
    try:
        json_str = clean_llm_response(final_message)
        data = json_repair.loads(json_str)
        return UIDesignerOutput(**data)
    except Exception as e:
        print(f"⚠️ [UIDesigner] Error parsing JSON output: {e}")
        # Fallback empty UI
        return UIDesignerOutput(
            project_name=architect_output.project_name,
            design_system_notes="Could not parse Stitch output.",
            screens=[]
        )
