from typing import List
from pydantic import BaseModel, Field
from config.llm_config import llm_designer
from tools.llm_helpers import clean_llm_response
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.prebuilt import create_react_agent

from agents.architect_agent import ArchitectOutput
from agents.stitch_mcp import StitchMCPClient
import json_repair

# ── Pydantic Models ────────────────────────────────────────────────────────────

class UIScreen(BaseModel):
    """Represents a generated UI screen."""
    name: str = Field(..., description="Name of the screen, e.g., 'Home', 'Dashboard'")
    description: str = Field(..., description="Description of the screen and its components")
    stitch_screen_url: str = Field(default="", description="The URL or resource name generated by Google Stitch")
    html_content: str = Field(default="", description="HTML content representation of the screen")

class UIDesignerOutput(BaseModel):
    """The final output from the UI Designer Agent."""
    project_name: str = Field(..., description="Name of the UI project")
    design_system_notes: str = Field(..., description="Notes on the generated design system (colors, typography, etc.)")
    screens: List[UIScreen] = Field(default_factory=list, description="List of generated UI screens")

# ── Prompts ────────────────────────────────────────────────────────────────────

UIDESIGNER_SYSTEM_PROMPT = """Eres el UI Designer Agent del equipo de desarrollo.
Tu trabajo es utilizar las herramientas de Google Stitch (disponibles a través de funciones) para generar las pantallas y el sistema de diseño del proyecto basándote en la arquitectura propuesta.

PROCESO A SEGUIR:
1. Crea un nuevo proyecto en Google Stitch (create_project) o usa uno existente.
2. Genera el sistema de diseño (create_design_system_from_design_md u otra).
3. Por cada vista necesaria en el frontend de la arquitectura, utiliza 'generate_screen_from_text' o 'create_screen' para construir la UI.
4. Cuando hayas terminado de generar las pantallas, DEBES generar tu salida final devolviendo UNICAMENTE un objeto JSON estructurado que cumpla con este formato:

```json
{
  "project_name": "Nombre",
  "design_system_notes": "...",
  "screens": [
    {
      "name": "Home",
      "description": "...",
      "stitch_screen_url": "projects/XYZ/screens/123"
    }
  ]
}
```
No incluyas texto fuera del JSON final."""

# ── Public API ─────────────────────────────────────────────────────────────────

def run_ui_designer_agent(architect_output: ArchitectOutput, stitch_api_key: str) -> UIDesignerOutput:
    """Uses Google Stitch to design UI screens based on the architecture."""
    
    # Initialize Stitch MCP Tools
    stitch_client = StitchMCPClient(api_key=stitch_api_key)
    try:
        tools = stitch_client.get_tools()
        print(f"🔧 [UIDesigner] Cargadas {len(tools)} herramientas de Google Stitch.")
    except Exception as e:
        print(f"⚠️ [UIDesigner] Error cargando herramientas de Stitch: {e}. Se ejecutará sin herramientas.")
        tools = []
        
    llm = llm_designer
    
    agent = create_react_agent(llm, tools=tools)
    
    arch_json = architect_output.model_dump_json(indent=2)
    
    # Combine the system prompt with the human message as the first prompt
    prompt = f"{UIDESIGNER_SYSTEM_PROMPT}\n\nAquí tienes la arquitectura del sistema:\n{arch_json}\n\nUsa las herramientas de Stitch para generar las pantallas, y luego devuelve el JSON estructurado."
    
    print("🎨 [UIDesigner] Generando pantallas con Google Stitch...")
    response = agent.invoke({"messages": [HumanMessage(content=prompt)]}, config={"recursion_limit": 10})
    
    final_message = response["messages"][-1].content
    
    # Parse the final JSON from the agent's last message
    try:
        json_str = clean_llm_response(final_message)
        data = json_repair.loads(json_str)
        return UIDesignerOutput(**data)
    except Exception as e:
        print(f"⚠️ [UIDesigner] Error parseando output JSON: {e}")
        # Fallback empty UI
        return UIDesignerOutput(
            project_name=architect_output.project_name,
            design_system_notes="No se pudo parsear el output de Stitch.",
            screens=[]
        )
